import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms of Service | Tenant Buddy",
  description: "Terms of Service for Tenant Buddy - your tenancy record organiser",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background-dark">
      <div className="max-w-3xl mx-auto px-4 py-12 md:py-16">
        {/* Back Link */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-text-subtle hover:text-primary transition-colors text-sm font-medium mb-8"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Home
        </Link>

        <article className="prose prose-invert prose-slate max-w-none">
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-8">
            Terms of Service
          </h1>

          <p className="text-text-subtle text-sm mb-8">
            Last updated: {new Date().toLocaleDateString("en-AU", { month: "long", day: "numeric", year: "numeric" })}
          </p>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              1. What This Service Is
            </h2>
            <p className="text-text-subtle leading-relaxed">
              This application is a digital tool designed to help users record, organise, and
              export their own tenancy-related information, such as issues, documents, photos,
              and notes, into structured records and PDF evidence packs.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              2. What This Service Is Not
            </h2>
            <p className="text-text-subtle leading-relaxed mb-4">
              This service does not provide legal advice, legal opinions, legal analysis,
              or outcome predictions.
            </p>
            <p className="text-text-subtle leading-relaxed">
              Any information generated or displayed by the application is for general
              information and record-keeping purposes only and should not be relied upon
              as legal advice.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              3. User Responsibility
            </h2>
            <p className="text-text-subtle leading-relaxed mb-4">
              You are solely responsible for:
            </p>
            <ul className="list-disc pl-6 text-text-subtle space-y-2 mb-4">
              <li>The accuracy of the information you enter</li>
              <li>How you use any exported evidence packs or documents</li>
              <li>Any decisions or actions you take based on your records</li>
            </ul>
            <p className="text-text-subtle leading-relaxed">
              You should seek independent advice from a qualified professional or tenants&apos;
              union before making legal decisions.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              4. No Professional Relationship
            </h2>
            <p className="text-text-subtle leading-relaxed">
              Use of this service does not create a lawyer–client, advisor–client, or
              professional relationship of any kind.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              5. AI-Assisted Features
            </h2>
            <p className="text-text-subtle leading-relaxed mb-4">
              Some features may use automated or AI-assisted processes to help organise
              information or generate draft content.
            </p>
            <p className="text-text-subtle leading-relaxed mb-4">
              These features:
            </p>
            <ul className="list-disc pl-6 text-text-subtle space-y-2">
              <li>Do not assess legal rights or outcomes</li>
              <li>Do not interpret laws or regulations</li>
              <li>Provide drafts and summaries that must be reviewed and edited by you before use</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              6. Evidence Packs
            </h2>
            <p className="text-text-subtle leading-relaxed mb-4">
              Any evidence packs or documents generated by the service are user-prepared
              records, compiled from information you provide.
            </p>
            <p className="text-text-subtle leading-relaxed">
              We do not guarantee acceptance, completeness, or suitability of any document
              for legal or administrative proceedings.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              7. Limitation of Liability
            </h2>
            <p className="text-text-subtle leading-relaxed">
              To the maximum extent permitted by law, we are not responsible for losses,
              damages, or outcomes arising from your use of the service or reliance on
              any generated content.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">
              8. Availability
            </h2>
            <p className="text-text-subtle leading-relaxed">
              We may modify, suspend, or discontinue features at any time. We do not
              guarantee uninterrupted access.
            </p>
          </section>

          {/* Footer Links */}
          <div className="border-t border-card-lighter pt-8 mt-12">
            <p className="text-text-subtle text-sm">
              See also: <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>
            </p>
          </div>
        </article>
      </div>
    </div>
  );
}
